### ISSUE TITLE
[HELP] Installing FileRise on Synology NAS

### ISSUE THREAD

**Issue by signo1337** [error311/FileRise#66]
Hey there

Finally found time to test your recent changes, very exciting! Unfortunately I can't get FileRise to work properly on my Synology NAS. 

I have a dedicated shared folder where I save all my training videos, let's assume a user named "training" as sole owner of it. The provided docker-compose was adapted accordingly for correct file paths and UID / GID of the "training" user.

At first I mapped the metadata and users folder from my /volume1/docker/filerise folder, and in a second attempt I mapped them directly from the shared folder (together with the uploads, i.e. the actual training videos). 

Both versions let me sign in to FileRise, but then it seems to be super slow, listing some of the files on the left side, but does not let me click on anything. The logs don't indicate anything wrong. 

First assumption is incorrect permissions (but then, why?), and the second thought would be that my training video library is just too massive (currently around 1-3 TB, not sure exactly). 

Thanks a lot!

**Comment by error311** [comment]
You can change the env variable SCAN_ON_START to false should resolve the massive library scan every time. 

Can you also provide the container console logs?

**Comment by signo1337** [comment]
> You can change the env variable SCAN_ON_START to false should resolve the massive library scan every time.
> 
> Can you also provide the container console logs?

Still not working for me. Maybe permission issue after all, although the user that owns the files is the same as I defined in docker compose.

**Comment by error311** [comment]
I been working on folder management improvements since v1.9.0. I am working on lazy loading of the fold tree which might resolve your issue. I will keep this open until I finish that.

**Comment by error311** [comment]
@signo1337 you willing to test an updated folderManager.js and a new endpoint for me? You would just need to replace public/js/folderManager.js and add a new public/api/folder/listChildren.php. Let me know if you comfortable and willing to do that. 

Edit: Here are the two files and where they go in public folder. There some issues such as missing chevrons and buttons ain't hooked up but this should tell us if this lazy loading will solve your large library issues. 
[FileRise-v1.9.3_1.zip](https://github.com/user-attachments/files/23491676/FileRise-v1.9.3_1.zip)

**Comment by signo1337** [comment]
> 
> @signo1337 you willing to test an updated folderManager.js and a new endpoint for me? You would just need to replace public/js/folderManager.js and add a new public/api/folder/listChildren.php. Let me know if you comfortable and willing to do that. 
> 
> Edit: Here are the two files and where they go in public folder. There some issues such as missing chevrons and buttons ain't hooked up but this should tell us if this lazy loading will solve your large library issues. 
> [FileRise-v1.9.3_1.zip](https://github.com/user-attachments/files/23491676/FileRise-v1.9.3_1.zip)

Hey there

Basically I am not against testing it, but atm I am mostly on mobile phone so tinkering with docker images or files therein is not feasible. Do you have a test branch / docker image tag by chance? If yes I could quickly swap the tag and redeploy the container with my phone.

**Comment by error311** [comment]
Thanks @signo1337 but I think I will be dropping the release tonight. Everything is looking good from my testing and I tested with a very large library.

**Comment by error311** [comment]
Hey@signo1337 
I just shipped a big folder tree overhaul that specifically targets huge libraries and slow NAS mounts.

- Lazy folder tree (no full recursive scan on load)
- Cursor pagination + “Load more” at each level (100 max)
- ACL-safe chevrons (you can expand locked parents without leaking file counts)
- Smarter initial selection (lands on your first accessible folder)

If this doesn't resolve your issue we can look into Synology permissions as possible cause. FileRise’s folder tree is now designed to handle 100k+ folders via lazy loading and cursor pagination. Even very large libraries remain responsive, as only a small page of nodes is rendered at a time.

Please if you can give me your feedback on the latest release. I appreciate your help.

**Comment by signo1337** [comment]
> Hey@signo1337 
> I just shipped a big folder tree overhaul that specifically targets huge libraries and slow NAS mounts.
> 
> - Lazy folder tree (no full recursive scan on load)
> - Cursor pagination + “Load more” at each level (100 max folders)
> - ACL-safe chevrons (you can expand locked parents without leaking file counts)
> - Smarter initial selection (lands on your first accessible folder)
> 
> If this doesn't resolve your issue we can look into Synology permissions as possible cause. FileRise’s folder tree is now designed to handle 100k+ folders via lazy loading and cursor pagination. Even very large libraries remain responsive, as only a small page of nodes is rendered at a time.
> 
> Please if you can give me your feedback on the latest release. I appreciate your help.

Hey there

Thanks for your astonishing work! 

I just tested the newest release (on my mobile...) and it definitely seems to be much better now. Folders load, I can browse the files. Will need to test on my desktop more thoroughly. 

But, I like it, also the more polished UI - great job!

**Comment by error311** [comment]
Awesome thanks so much for creating the issue and bringing this to my attention. Glad we were able to resolve your issue.

Any new issues you find or features you want, let me know!

**Comment by signo1337** [comment]
> Awesome thanks so much for creating the issue and bringing this to my attention. Glad we were able to resolve your issue.
> 
> Any new issues you find or features you want, let me know!

Hey there

Just tried filerise from my desktop computer - so far a nice experience. Also the "watched" tag helps a lot. But... The mobile experience seems not yet fully enjoyable, but maybe I am missing some settings. For example (blurring done by me, not the app :D):

<img width="430" height="934" alt="Image" src="https://github.com/user-attachments/assets/cf64303c-8237-4883-acf4-9d09f21a77ae" />

Just letting you know, not complaining about anything :) Thx!

**Comment by error311** [comment]
@signo1337 you can go to User Panel and uncheck "Show folders above files". Those do not lazy load yet.

**Comment by error311** [comment]
@signo1337 how can we resolve this issue for you? Add a Load more after 50 folders? Truncate the folder name or wrap long folder names?

Another option might be disable the folder strip on mobile devices

**Comment by signo1337** [comment]
> @signo1337 how can we resolve this issue for you? Add a Load more after 50 folders? Truncate the folder name or wrap long folder names?
> 
> Another option might be disable the folder strip on mobile devices

Maybe as list view. If folder name too long, continue on next line. That's how Synology Drive shows the folders. I like Synology Drive very much actually, but they lack the progress saving and "watched" feature. Which is crucial for me with tons of training videos.

**Comment by error311** [comment]
I limited the width of folder strip and allow it to wrap. Hopefully this looks a little better for you. I still plan to add the lazy loading into the strip too so the list only goes to 50 until you load more. 

Not really sure how Synology Drive shows the folders? If you could share an example could be helpful or give us an idea of how to improve filerise.

**Comment by signo1337** [comment]
> I limited the width of folder strip and allow it to wrap. Hopefully this looks a little better for you. I still plan to add the lazy loading into the strip too so the list only goes to 50 until you load more. 
> 
> Not really sure how Synology Drive shows the folders? If you could share an example could be helpful or give us an idea of how to improve filerise. 

Well its pretty basic but still sleek:

![image](https://github.com/user-attachments/assets/7fdc9e6c-aad1-4538-9895-ed6bcd6b0d25)

**Comment by signo1337** [comment]
@error311 Hey :) I just wanted to get back to you to say how much I am starting to love filerise. I appreciate very much your openness to improvements, and also your knowledge to make these changes. I am considering buying the pro version even, just to support you and because i like this project. Maybe UI could be tweaked a bit, or mobile app support (ofc) for direct file sharing / uploading from another app (i know, app support probably way out of scope). But it seems on a perfectly good way. Anyways, thumbs up and a huge thank you.

**Comment by error311** [comment]
@signo1337 thank you so much.

I appreciate the support you already given. Any additional feature request or issues you have submitted will continue to improve FileRise. I agree UI does need a bit of work which I try to constantly tweak. Also I do plan to build a mobile/desktop sync app but that probably far off the roadmap.

I have been testing some folder strip changes that similar to picture you shared for only mobile devices. Might work out nice will let you know once I have that finished.

**Comment by error311** [comment]
Hey @signo1337 

I adjusted the folder strip to be similar to what you shared on mobile devices only. Also added a simple lazy-loading for the strip  too.

<img width="540" height="866" alt="Image" src="https://github.com/user-attachments/assets/8160c45d-d598-4173-ac5d-2df36e2642e4" />

**Comment by signo1337** [comment]
> Hey @signo1337 
> 
> I adjusted the folder strip to be similar to what you shared on mobile devices only. Also added a simple lazy-loading for the strip  too.
> 
> <img width="540" height="866" alt="Image" src="https://github.com/user-attachments/assets/8160c45d-d598-4173-ac5d-2df36e2642e4" />

Just amazing how much work you pour into this project and to see your eagerness to continuously improve!

Looking good - ai just tested the mobile view again, and now I know what it is that I might miss: the whole UI seems to be divided into two parts: folder structure only as one part, and the content thereof as separate part. Might be much more convenient to just browse the folder structure and see the files right there in the same view instead of having to scroll down to file view panel?

**Comment by error311** [comment]
Thanks for kind words sig.

So you mean keep the folders in the file list view? I did have filerise like this in the beginning but I ended up going folder tree only and added folders back above file list view.

I think that is a good idea for mobile devices. I'll look into improving it some more for sure.

**Comment by signo1337** [comment]
> Thanks for kind words sig.
> 
> So you mean keep the folders in the file list view? I did have filerise like this in the beginning but I ended up going folder tree only and added folders back above file list view.
> 
> I think that is a good idea for mobile devices. I'll look into improving it some more for sure.

Bacisally standard folder browsing as known from Windows/MacOS or mobile file explorers. So folder tree and file list combined, in both the mobile and desktop view :)

**Comment by error311** [comment]
Gotcha yeah it was like that but I wanted to keep focus on File aspect I guess in the file list.

I do what want to move the folder list how it is down right above the file list or apart of it in a better way.

I could add to user panel a toggled to show normal in the file list like you're suggesting. I would like both options at least since I like them separate. 

Thanks again for your suggestions. I will add that option in if it works for you.

**Comment by signo1337** [comment]
> Gotcha yeah it was like that but I wanted to keep focus on File aspect I guess in the file list.
> 
> I do what want to move the folder list how it is down right above the file list or apart of it in a better way.
> 
> I could add to user panel a toggled to show normal in the file list like you're suggesting. I would like both options at least since I like them separate. 
> 
> Thanks again for your suggestions. I will add that option in if it works for you.

Making it as an option is a very nice way of course to suit the taste of different users 👌

Looking very much forward to the release :)

**Comment by error311** [comment]
@signo1337 

Update tonight will have what you asked for 😄 

Edit: I like it so much it will now be the default view lol. Thanks so much for mentioning it. 

Heres a peak

<img width="1128" height="589" alt="Image" src="https://github.com/user-attachments/assets/f1493449-f753-4415-add3-4984aa65a05f" />

<img width="621" height="518" alt="Image" src="https://github.com/user-attachments/assets/6b39a8b2-d914-4f0d-a35a-93e0813afcd9" />

**Comment by error311** [comment]
@signo1337 it's released let me know what you think

**Comment by signo1337** [comment]
> [@signo1337](https://github.com/signo1337) it's released let me know what you think

hey! once more, great work. The "Folder Navigation & Management" Panel would be obsolete when the new option is active (but is still there - in that setup kind of overkill in my opinion). Also, in the new view I can't go back to the root directory. 

<img width="1888" height="902" alt="Image" src="https://github.com/user-attachments/assets/f3a05707-e6a8-4c16-ae33-4659de2b8001" />

**Comment by error311** [comment]
> > [@signo1337](https://github.com/signo1337) it's released let me know what you think
> 
> hey! once more, great work. The "Folder Navigation & Management" Panel would be obsolete when the new option is active (but is still there - in that setup kind of overkill in my opinion). Also, in the new view I can't go back to the root directory.
> 


Thanks @signo1337.

They both active for you since it was active your previous session. If you open in private tab it will only show the inline folder view. By default inline folders are enabled and folder strips are disabled.

Not displaying root in folders and breadcrumb is related to old code that I have not yet fixed. I also was planning "Spaces" where you can turn any folder into its own "space" which has its own users and ACL permissions. That was my plan for FileRise v2.0.0 but I think I am going to do client portal for v2.0.0 and maybe Spaces in v2.2. I will fix the root display issue before v2.0.0 though.

**Comment by signo1337** [comment]
> > > [@signo1337](https://github.com/signo1337) it's released let me know what you think
> > 
> > hey! once more, great work. The "Folder Navigation & Management" Panel would be obsolete when the new option is active (but is still there - in that setup kind of overkill in my opinion). Also, in the new view I can't go back to the root directory.
> > 
> 
> 
> Thanks @signo1337.
> 
> They both active for you since it was active your previous session. If you open in private tab it will only show the inline folder view. By default inline folders are enabled and folder strips are disabled.
> 
> Not displaying root in folders and breadcrumb is related to old code that I have not yet fixed. I also was planning "Spaces" where you can turn any folder into its own "space" which has its own users and ACL permissions. That was my plan for FileRise v2.0.0 but I think I am going to do client portal for v2.0.0 and maybe Spaces in v2.2. I will fix the root display issue before v2.0.0 though.
> 

Oh yea nice, works also in mobile. Still a bit laggy though compared to for example Synology Drive, but great in terms of functionality :) of course, not a complaint, just an observation. Maybe something can be tune or improved for faster speeds.

Also, roadmap sounds super interesting. Seems like you never run out of ideas, nor motivation - great job!

**Comment by error311** [comment]
I'll look into tweaking performance. I did attempt to make performance good but it has to go through ACL and folder details plus no lazy loading of folders like the folder strip has. Synology also from what I've read does some additional file level stuff that might cause you performance issues.

Thanks I hope to just continue improving and adding new features to FileRise. Another plan feature I have would be Search Everything. Have this respect ACL and toggle indexing per folder. 

More coming would be multiple storages (local, archive & s3), support for plugins and customized logging.

**Comment by error311** [comment]
Breadcrumb not showing root was fixed @signo1337

**Comment by signo1337** [comment]
> Breadcrumb not showing root was fixed @signo1337 
> 

Nice, just pulled latest image and it's fixed. Good work!

**Comment by signo1337** [comment]
Do you run by chance any black friday discount for the pro version? :)

**Comment by error311** [comment]
> Do you run by chance any black friday discount for the pro version? :)

This is a great idea. I just added BLACKFRIDAY30 code for 30% off until December 1st. I'll add a banner to main site.

**Comment by signo1337** [comment]
> > Do you run by chance any black friday discount for the pro version? :)
> 
> This is a great idea. I just added BLACKFRIDAY30 code for 30% off until December 1st. I'll add a banner to main site.

Cool, thanks. Just bought it :)

**Comment by error311** [comment]
@signo1337 Huge thanks for grabbing Pro and for all your support! 

If you hit any issues or have feature ideas, just ping me at error311@gmail.com. Hope you enjoy FileRise Pro!
