### ISSUE TITLE
Deploy to a subpath

### ISSUE THREAD

**Issue by ecraven** [error311/FileRise#73]
**Describe the bug**
I'd like to deploy filerise to example.com/fr *not* to a root (like fr.example.com/)

**To Reproduce**
Deploy filerise, set up the reverse proxy to strip /fr.

**Expected behavior**
Working filerise.

**What happens**
Network requests to `/css`, `/vendor`, etc.

Is there any way to either set the full path that filerise runs at or to have filerise be *independent* of the actual path?

**Comment by error311** [comment]
@ecraven Do not strip the prefix. Instead, proxy /fr/ and keep /fr in the upstream request path so PHP sees it and FileRise can generate URLs correctly. (FileRise manual installs are meant to be able to live in a subfolder. )

Nginx (don’t strip)
```
location /fr/ {
  proxy_pass http://filerise:80;   # NOTE: no trailing slash = preserves /fr/...
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

Caddy (don’t use handle_path)
```
example.com {
  redir /fr /fr/
  handle /fr/* {
    reverse_proxy localhost:8080
  }
}
```
(handle_path strips by design, which causes the broken /css//vendor requests.  ￼)

Traefik
Avoid StripPrefix(/fr) middleware; route /fr without stripping.

One more note (share links)

If you run under /fr, set BASE_URL to include it (e.g. https://example.com/fr) so generated share links are correct. FileRise uses BASE_URL for building absolute share URLs.

**Comment by ecraven** [comment]
I'm running this behind traefik in a simple k8s cluster. I have the following configuration:
```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filerise
  namespace: filerise
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`www.example.com`) && PathPrefix(`/fr`)
      kind: Rule
      services:
        - name: filerise
          port: 8080
  tls:
    secretName: www-example-com-tls
```

I see the following output from the filerise pod:
```
10.42.0.140 - - [15/Dec/2025:07:30:28 +0000] "GET /fr/ HTTP/1.1" 404 1136 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Gecko/20100101 Firefox/145.0"
```

So it doesn't seem to like `/fr/`. I have set `BASE_URL`, do I need to set any *other* environment variables?
```
          env:
            - name: TIMEZONE
              value: "Europe/Paris"
            - name: TOTAL_UPLOAD_SIZE
              value: "10G"
            - name: LOG_STREAM
              value: "both"
            - name: SECURE
              value: "true"
            - name: BASE_URL
              value: "https://www.example.com/fr/"
            - name: PERSISTENT_TOKENS_KEY
              value: "MyVerySecretSecret"
            - name: SCAN_ON_START
              value: "false"      # index existing files on first run
            - name: CHOWN_ON_START
              value: "true"      # fix ownership on first run
```

**Comment by error311** [comment]
Working on a permanent solution controllable with env var or admin panel @ecraven 

<img width="941" height="751" alt="Image" src="https://github.com/user-attachments/assets/ac786d75-3d0a-415e-b482-5338cee47a77" />

**Comment by error311** [comment]
Thanks @ecraven for the detailed report and config. I marked this closed as fixed in current FileRise releases. 

FileRise now fully supports running behind a reverse proxy on a subpath (e.g. /fr) without any strip-prefix workarounds. Asset URLs, API calls, portals, PWA, and share links are all generated base-path aware.

I’ve verified this locally with Nginx using a /fr deployment and confirmed it works as expected without special routing tricks.

For Traefik/Kubernetes, you should be able to keep a simple PathPrefix(/fr) rule (no StripPrefix middleware) and just ensure your published URL is set to https://www.example.com/fr. No additional environment variables are required.

I’m going to mark this issue as resolved, but feel free to reopen if you still see anything odd in your setup.

**Comment by ecraven** [comment]
I still get the same behaviour as before, I see the following in the apache log:
```
10.42.0.39 - - [19/Dec/2025:09:35:20 +0000] "GET /fr/ HTTP/1.1" 404 1136 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Gecko/20100101 Firefox/145.0"
```
My traefik setup:
```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filerise
  namespace: filerise
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`www.example.com`) && PathPrefix(`/fr`)
      kind: Rule
      services:
        - name: filerise
          port: 8080
  tls:
    secretName: www-example-com-tls

```
so it seems the traffic goes through to the filerise pod correctly, but apache then doesn't know what to do with it. I don't understand how you can make this work without *knowing* under which path it's supposed to run? Shouldn't I need to configure that somewhere?
I don't have permissions to re-open this (and the problem might well be on my side entirely ;) )

**Comment by error311** [comment]
@ecraven You can set the path in FileRise two ways:

- Admin Panel > Proxy / Firewall > Published URL: https://www.example.com/fr
or
- env var: FR_PUBLISHED_URL=https://www.example.com/fr

Let me know if this resolves your issue.

**Comment by ecraven** [comment]
the first wouldn't work, as I can't *access* it ;) I tried the second, with the v2.10.5 docker image in kubernetes:
```
          env:
            - name: FR_PUBLISHED_URL
              value: "https://www.example.com/fr/"
```
but no luck.. apache 404.
I also tried setting `FR_BASE_PATH`, no luck either.

**Comment by ecraven** [comment]
This is the message I get from apache:
```
Not Found

The requested URL was not found on this server.
Apache/2.4.58 (Ubuntu) Server at www.example.com Port 80
```
This must be from the internal apache, I don't have apache running anywhere else. it also correlates with the loglines of the container.

**Comment by error311** [comment]
@ecraven Thank you.
That `GET /fr/ ... 404` confirms the request is reaching the pod, but the backend is still receiving `/fr/...` paths and routing isn’t treating `/fr` as the mount point.

For Traefik/Kubernetes, the correct pattern is:
- route `PathPrefix(`/fr`)` at the edge
- **StripPrefix `/fr` before forwarding to the FileRise service**
- rely on Traefik’s StripPrefix behavior which stores the removed prefix in `X-Forwarded-Prefix` (FileRise reads this for base-path aware URL generation).

Can you try this CRD setup:

```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: filerise-strip-fr
  namespace: filerise
spec:
  stripPrefix:
    prefixes:
      - /fr
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filerise
  namespace: filerise
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`www.example.com`) && PathPrefix(`/fr`)
      kind: Rule
      middlewares:
        - name: filerise-strip-fr
      services:
        - name: filerise
          port: 8080
  tls:
    secretName: www-example-com-tls
```

And set (no trailing slash):

```
- name: FR_PUBLISHED_URL
  value: "https://www.example.com/fr"
```

FR_BASE_PATH should not be necessary with the middleware because Traefik will provide X-Forwarded-Prefix: /fr.

After applying, https://www.example.com/fr/ should load and assets/API should resolve under /fr/....
If you still get a 404, paste the response headers/body of `curl -i https://www.example.com/fr/` and I’ll dig in.

**Comment by ecraven** [comment]
> For Traefik/Kubernetes, you should be able to keep a simple PathPrefix(/fr) rule (no StripPrefix middleware) and just ensure your published URL is set to https://www.example.com/fr. No additional environment variables are required.

Sorry, this confused me, as you say, if I add stripping the prefix, everything works perfectly! thank you very much for fixing this so quickly!

**Comment by error311** [comment]
@ecraven Awesome so glad you were able to resolve it. Sorry about the confusion. I went through wiki and readme to try and make it more clear now.
